{{- if not .Values.certManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ template "contrast-agent-injector.name" . }}-admission
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "contrast-agent-injector.name" $ }}-admission
{{ include "contrast-agent-injector.labels" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "contrast-agent-injector.name" . }}-admission
subjects:
  - kind: ServiceAccount
    name: {{ template "contrast-agent-injector.name" . }}-admission
    namespace: {{ .Release.Namespace }}
{{- end }}