apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contrast-agent-injector.name" . }}
  labels:
    {{- include "contrast-agent-injector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "contrast-agent-injector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "contrast-agent-injector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "contrast-agent-injector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tlsCertFile
            - /etc/webhook/tls.crt
            - --tlsKeyFile
            - /etc/webhook/tls.key
            - --secretName
            - "{{ .Values.contrast.secretName }}"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
          - name: tls-cert
            mountPath: /etc/webhook
          livenessProbe:
            httpGet:
              path: /live
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: tls-cert
        secret:
          secretName: {{ template "contrast-agent-injector.name" . }}-admission
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
